### ISSUE TITLE
What if the config file isn't called default.yml?

### ISSUE THREAD

**Issue by bookercodes** [KidkArolis/ava-config#1]
I noticed that you hard-coded [`default.yml`](https://github.com/KidkArolis/ava-config/blob/master/index.js#L23).

I use a different feature of `config` to load confiugration files based on the environment variable name.

So whereas my test files are called `development.json` and `test.json`, this module doesn't pick them up.

Is this something you're interested in supporting? Thanks.

**Comment by hgrubst** [comment]
I also hit the same issue.
An easy fix is to not look for a specific file name, because `config` module does not impose you to have a file called 'default.EXT',  but just for a folder named _config_ up the tree.
Also, the search currently starts at `__dirname`. This is the `ava-config` folder itself. I changed the logic to start 2 folders up, so that the search starts outside `node_modules` (and so does not pick up the folder of the `config` module itself)
I'll try to put a PR if I get some time.

**Comment by yamsellem** [comment]
@alexbooker @hgrubst may you please merge the branch? Here, we use a .json config file, so this module don't work (and for so little thing, it's sad).

**Comment by KidkArolis** [comment]
Oh my! I never realised there were issues/PRs on this repo, cause I wasn't watching it. Fail. Sorry about that.

I guess this might not be relevant to you anymore, especially if latest `ava` changed the cwd behaviour.

In any case, I'll merge and release the PR.
